### ISSUE TITLE
Fatal error - add_item

### ISSUE THREAD

**Issue by DannyAgMs** [microsoft/git#540] opened 2022-10-24 16:23 UTC
- [x] I was not able to find an [open](https://github.com/microsoft/git/issues?q=is%3Aopen)
        or [closed](https://github.com/microsoft/git/issues?q=is%3Aclosed) issue matching
        what I'm seeing, including in [the `git-for-windows/git` tracker](https://github.com/git-for-windows/git/issues).

### Setup

 - Which version of `microsoft/git` are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.36.0.vfs.0.0
cpu: x86_64
built from commit: 5323cc6ccf2923f4f41da713ea9d1125704dec5b
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

Are you using Scalar or VFS for Git?

Scalar

If VFS for Git, then what version?

```
$ gvfs version

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

10.0.22621.674
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git status
```
 - What did you expect to occur after running these commands?

Display differences between working tree and index

 - What actually happened instead?

D:\OMR\src\word\core>git status
      0 [main] sh (39536) C:\Program Files\Git\usr\bin\sh.exe: *** fatal error - add_item ("\??\C:\Program Files\Git", "/", ...) failed, errno 1
Stack trace:
Frame        Function    Args
000FFFFCD30  00210062B0E (0021029B02A, 00210275E51, 00000000000, 000FFFF8B30)
000FFFFCD30  0021004846A (00000000000, 000FFFFCD30, 00210020010, 000FFFFABF0)
000FFFFCD30  002100484A2 (000FFFF9BC0, 00000000001, 00000000000, 00000000001)
000FFFFCD30  002100ED357 (00000000000, 00000000000, 000FFFFFFFF, 00000000000)
000FFFFCD30  00210132A75 (002100DC294, 00000000000, 00000000000, 00000000000)
000FFFFCD30  00210048AB8 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00210047716 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  002100477C4 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
On branch user/tiagoma/ado_6859943
You are in a sparse checkout.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   fileenc.cpp
no changes added to commit (use "git add" and/or "git commit -a")
      0 [main] sh (46236) C:\Program Files\Git\usr\bin\sh.exe: *** fatal error - add_item ("\??\C:\Program Files\Git", "/", ...) failed, errno 1
Stack trace:
Frame        Function    Args
000FFFFCD30  00210062B0E (0021029B02A, 00210275E51, 00000000000, 000FFFF8B30)
000FFFFCD30  0021004846A (00000000000, 000FFFFCD30, 00210020010, 000FFFFABF0)
000FFFFCD30  002100484A2 (000FFFF9BC0, 00000000001, 00000000000, 00000000001)
000FFFFCD30  002100ED357 (00000000000, 00000000000, 000FFFFFFFF, 00000000000)
000FFFFCD30  00210132A75 (002100DC294, 00000000000, 00000000000, 00000000000)
000FFFFCD30  00210048AB8 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00210047716 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  002100477C4 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace

 - If the problem was occurring with a specific repository, can you specify
   the repository?

   * [ ] Public repo: **insert URL here**
   * [ ] Windows monorepo
   * [x] Office monorepo
   * [ ] Other Microsoft-internal repo: **insert name here**
   * [ ] Other internal repo.

**Comment by derrickstolee** [comment] 2022-10-24 17:42
Hi, @DannyAgMs. Thanks for the report.

Could you repeat the `git status` command with `GIT_TRACE2_PERF=1` enabled? That should help us identify a closer location for where this failure happened.

Since the `git status` command continued after the error (and the error appears to be in `sh.exe`) it seems like the failure is due to a hook of some kind. The `GIT_TRACE2_PERF` output should show this immediately.

**Comment by dscho** [comment] 2022-11-09 16:40
This symptom occasionally occurs in Git for Windows, too, and it stems from the Cygwin/MSYS2 runtime spinning up concurrently (and the concurrent instances stumbling over each other).

It seems to happen quite rarely and seems to be hard to reproduce, so I am not sure that we can do anything about this for now.

**Comment by DannyAgMs** [comment] 2022-11-09 18:05
We haven't seen any recent instances either and are unable to reproduce.

**Comment by dscho** [comment] 2022-11-11 13:32
So let's close this for now, we can always re-open later.

**Closed as not planned by dscho** 2022-11-11 13:32 UTC
