### ISSUE TITLE
"git diff-index HEAD --" take 46s+ to finish

### ISSUE THREAD

**Issue by miku1958** [microsoft/git#545] opened 2022-11-19 04:54 UTC
- [x] I was not able to find an [open](https://github.com/microsoft/git/issues?q=is%3Aopen)
        or [closed](https://github.com/microsoft/git/issues?q=is%3Aclosed) issue matching
        what I'm seeing, including in [the `git-for-windows/git` tracker](https://github.com/git-for-windows/git/issues).

### Setup

 - Which version of `microsoft/git` are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.38.1.vfs.0.0
cpu: x86_64
built from commit: 0de34d54680002380b4e1adad74db64a34e03053
sizeof-long: 8
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

Are you using Scalar or VFS for Git?

Scalar

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I set config feature.manyfiles to true and sparse checkout these folders:
>git sparse-checkout set --sparse-index \\
otools \\
outlookmac \\
platformsdk/apple \\
mbu \\
identity/apple \\
liblet/apple \\
liblet/precomp \\
ofc/precomp \\
sdk/mapisdk \\
sdk/microsoft.windows.coresdk.mock \\
sdk/xplatwin \\
winsrc/os \\
winsrc/projects \\
winsrc/public

Almost 16k files

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

zsh

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git diff-index HEAD --
```
 - What did you expect to occur after running these commands?

as fast as "git status", on my machine it took 2s to 5s

 - What actually happened instead?

this command take 24s to run "label:ensure_full_index" and 20s to run "label:update", here is the call stack 
>% git diff-index HEAD --
12:40:04.606377 common-main.c:49             | d0 | main                     | version      |     |           |           |              | 2.38.1.vfs.0.0
12:40:04.606855 common-main.c:50             | d0 | main                     | start        |     |  0.001419 |           |              | git diff-index HEAD --
12:40:04.607512 repository.c:136             | d0 | main                     | def_repo     | r1  |           |           |              | worktree:/Volumes/Source/Office.monorepo/src
12:40:04.608716 git.c:533                    | d0 | main                     | cmd_name     |     |           |           |              | diff-index (diff-index)
12:40:04.614624 midx.c:173                   | d0 | main                     | data         | r1  |  0.009191 |  0.009191 | midx         | load/num_packs:114
12:40:04.614645 midx.c:174                   | d0 | main                     | data         | r1  |  0.009215 |  0.009215 | midx         | load/num_objects:6572781
12:40:05.392678 read-cache.c:2490            | d0 | main                     | region_enter | r1  |  0.787246 |           | index        | label:do_read_index .git/index
12:40:05.393945 read-cache.c:2131            | d0 | th01:load_index_extensio | thread_start |     |  0.788482 |           |              | 
12:40:05.393971 read-cache.c:2214            | d0 | th02:load_cache_entries  | thread_start |     |  0.788515 |           |              | 
12:40:05.393979 read-cache.c:2214            | d0 | th03:load_cache_entries  | thread_start |     |  0.788545 |           |              | 
12:40:05.393984 read-cache.c:1858            | d0 | th01:load_index_extensio | region_enter |     |  0.788555 |           | index        | label:read/extension/cache_tree
12:40:05.394000 cache-tree.c:663             | d0 | th01:load_index_extensio | region_enter | r1  |  0.788568 |           | cache_tree   | ..label:read
12:40:05.393990 read-cache.c:2214            | d0 | th04:load_cache_entries  | thread_start |     |  0.788556 |           |              | 
12:40:05.394063 read-cache.c:2214            | d0 | th05:load_cache_entries  | thread_start |     |  0.788620 |           |              | 
12:40:05.394075 read-cache.c:2214            | d0 | th07:load_cache_entries  | thread_start |     |  0.788637 |           |              | 
12:40:05.394076 read-cache.c:2214            | d0 | th06:load_cache_entries  | thread_start |     |  0.788593 |           |              | 
12:40:05.394112 read-cache.c:2214            | d0 | th10:load_cache_entries  | thread_start |     |  0.788676 |           |              | 
12:40:05.394100 read-cache.c:2214            | d0 | th08:load_cache_entries  | thread_start |     |  0.788634 |           |              | 
12:40:05.394104 read-cache.c:2214            | d0 | th09:load_cache_entries  | thread_start |     |  0.788637 |           |              | 
12:40:05.394196 read-cache.c:2214            | d0 | th11:load_cache_entries  | thread_start |     |  0.788764 |           |              | 
12:40:05.394202 read-cache.c:2214            | d0 | th12:load_cache_entries  | thread_start |     |  0.788688 |           |              | 
12:40:05.394254 read-cache.c:2214            | d0 | th13:load_cache_entries  | thread_start |     |  0.788817 |           |              | 
12:40:05.394314 read-cache.c:2214            | d0 | th14:load_cache_entries  | thread_start |     |  0.788858 |           |              | 
12:40:05.394439 read-cache.c:2214            | d0 | th15:load_cache_entries  | thread_start |     |  0.789006 |           |              | 
12:40:05.395431 read-cache.c:2214            | d0 | th16:load_cache_entries  | thread_start |     |  0.789997 |           |              | 
12:40:05.397393 read-cache.c:2223            | d0 | th02:load_cache_entries  | thread_exit  |     |  0.791962 |  0.003447 |              | 
12:40:05.397567 read-cache.c:2223            | d0 | th04:load_cache_entries  | thread_exit  |     |  0.792137 |  0.003581 |              | 
12:40:05.397653 read-cache.c:2223            | d0 | th03:load_cache_entries  | thread_exit  |     |  0.792223 |  0.003678 |              | 
12:40:05.397660 read-cache.c:2223            | d0 | th06:load_cache_entries  | thread_exit  |     |  0.792230 |  0.003637 |              | 
12:40:05.397683 read-cache.c:2223            | d0 | th08:load_cache_entries  | thread_exit  |     |  0.792253 |  0.003619 |              | 
12:40:05.397899 read-cache.c:2223            | d0 | th05:load_cache_entries  | thread_exit  |     |  0.792469 |  0.003849 |              | 
12:40:05.397929 read-cache.c:2223            | d0 | th10:load_cache_entries  | thread_exit  |     |  0.792499 |  0.003823 |              | 
12:40:05.398064 read-cache.c:2223            | d0 | th13:load_cache_entries  | thread_exit  |     |  0.792635 |  0.003818 |              | 
12:40:05.398163 read-cache.c:2223            | d0 | th07:load_cache_entries  | thread_exit  |     |  0.792733 |  0.004096 |              | 
12:40:05.398191 read-cache.c:2223            | d0 | th14:load_cache_entries  | thread_exit  |     |  0.792762 |  0.003904 |              | 
12:40:05.398266 read-cache.c:2223            | d0 | th15:load_cache_entries  | thread_exit  |     |  0.792836 |  0.003830 |              | 
12:40:05.398366 read-cache.c:2223            | d0 | th09:load_cache_entries  | thread_exit  |     |  0.792936 |  0.004299 |              | 
12:40:05.398448 read-cache.c:2223            | d0 | th11:load_cache_entries  | thread_exit  |     |  0.793018 |  0.004254 |              | 
12:40:05.398936 read-cache.c:2223            | d0 | th16:load_cache_entries  | thread_exit  |     |  0.793506 |  0.003509 |              | 
12:40:05.399662 read-cache.c:2223            | d0 | th12:load_cache_entries  | thread_exit  |     |  0.794232 |  0.005544 |              | 
12:40:05.406769 cache-tree.c:665             | d0 | th01:load_index_extensio | region_leave | r1  |  0.801338 |  0.012770 | cache_tree   | ..label:read
12:40:05.406781 read-cache.c:1860            | d0 | th01:load_index_extensio | data         |     |  0.801352 |  0.012797 | index        | ..read/extension/cache_tree/bytes:1177195
12:40:05.406787 read-cache.c:1861            | d0 | th01:load_index_extensio | region_leave |     |  0.801358 |  0.012803 | index        | label:read/extension/cache_tree
12:40:05.415405 fsmonitor.c:95               | d0 | th01:load_index_extensio | data         |     |  0.809972 |  0.021490 | index        | extension/fsmn/read/token:builtin:0.99664.20221119T030643.366709Z:0
12:40:05.415429 read-cache.c:2133            | d0 | th01:load_index_extensio | thread_exit  |     |  0.810000 |  0.021518 |              | 
12:40:05.415804 read-cache.c:2436            | d0 | main                     | data         | r1  |  0.810375 |  0.023129 | index        | ..read/version:4
12:40:05.415816 read-cache.c:2438            | d0 | main                     | data         | r1  |  0.810387 |  0.023141 | index        | ..read/cache_nr:165230
12:40:05.797036 cache-tree.c:512             | d0 | main                     | region_enter | r1  |  1.191594 |           | cache_tree   | ..label:update
12:40:07.367270 cache-tree.c:517             | d0 | main                     | region_leave | r1  |  2.761837 |  1.570243 | cache_tree   | ..label:update
12:40:07.367298 sparse-index.c:340           | d0 | main                     | region_enter | r1  |  2.761868 |           | index        | ..label:ensure_full_index
12:40:30.641384 cache-tree.c:512             | d0 | main                     | region_enter | r1  | 26.035950 |           | cache_tree   | ....label:update
12:40:50.898771 cache-tree.c:517             | d0 | main                     | region_leave | r1  | 46.293339 | 20.257389 | cache_tree   | ....label:update
12:40:50.898799 sparse-index.c:422           | d0 | main                     | region_leave | r1  | 46.293369 | 43.531501 | index        | ..label:ensure_full_index
12:40:50.898810 read-cache.c:2495            | d0 | main                     | region_leave | r1  | 46.293380 | 45.506134 | index        | label:do_read_index .git/index
12:40:50.922767 fsmonitor-ipc.c:80           | d0 | main                     | region_enter |     | 46.317335 |           | fsm_client   | label:query
12:40:50.922799 fsmonitor-ipc.c:81           | d0 | main                     | data         |     | 46.317369 |  0.000034 | fsm_client   | ..query/command:1668832850898858000
12:40:50.922821 ...ipc/ipc-unix-socket.c:162 | d0 | main                     | region_enter |     | 46.317391 |           | ipc-client   | ..label:try-connect
12:40:50.922833 ...ipc/ipc-unix-socket.c:163 | d0 | main                     | data         |     | 46.317404 |  0.000013 | ipc-client   | ....try-connect/path:.git/fsmonitor--daemon.ipc
12:40:50.922991 ...ipc/ipc-unix-socket.c:169 | d0 | main                     | data         |     | 46.317561 |  0.000170 | ipc-client   | ....try-connect/state:0
12:40:50.923008 ...ipc/ipc-unix-socket.c:170 | d0 | main                     | region_leave |     | 46.317578 |  0.000187 | ipc-client   | ..label:try-connect
12:40:50.923018 ...ipc/ipc-unix-socket.c:200 | d0 | main                     | region_enter |     | 46.317588 |           | ipc-client   | ..label:send-command
12:40:50.923224 ...ipc/ipc-unix-socket.c:217 | d0 | main                     | region_leave |     | 46.317791 |  0.000203 | ipc-client   | ..label:send-command
12:40:50.923257 fsmonitor-ipc.c:94           | d0 | main                     | data         |     | 46.317827 |  0.000492 | fsm_client   | ..query/response-length:43
12:40:50.923269 fsmonitor-ipc.c:131          | d0 | main                     | region_leave |     | 46.317840 |  0.000505 | fsm_client   | label:query
12:40:50.923280 fsmonitor.c:338              | d0 | main                     | data         |     | 46.317850 | 46.317850 | fsm_client   | query/trivial-response:1
12:40:50.923289 fsmonitor.c:439              | d0 | main                     | region_enter | r1  | 46.317859 |           | fsmonitor    | label:apply_results
12:40:50.949740 fsmonitor.c:500              | d0 | main                     | region_leave | r1  | 46.344304 |  0.026445 | fsmonitor    | label:apply_results
12:40:51.060921 preload-index.c:119          | d0 | main                     | region_enter |     | 46.455489 |           | index        | label:preload
12:40:51.301364 preload-index.c:167          | d0 | main                     | data         |     | 46.695933 |  0.240444 | index        | ..preload/sum_lstat:163448
12:40:51.301393 preload-index.c:168          | d0 | main                     | region_leave |     | 46.695963 |  0.240474 | index        | label:preload
12:40:51.303130 unpack-trees.c:1903          | d0 | main                     | region_enter |     | 46.697697 |           | unpack_trees | label:unpack_trees
12:40:51.303153 unpack-trees.c:1907          | d0 | main                     | region_enter | r1  | 46.697723 |           | unpack_trees | ..label:unpack_trees
12:40:51.337596 unpack-trees.c:2010          | d0 | main                     | region_enter | r1  | 46.732164 |           | unpack_trees | ....label:traverse_trees
12:40:51.555893 unpack-trees.c:2012          | d0 | main                     | region_leave | r1  | 46.950461 |  0.218297 | unpack_trees | ....label:traverse_trees
12:40:51.579049 unpack-trees.c:424           | d0 | main                     | region_enter |     | 46.973616 |           | unpack_trees | ....label:check_updates
12:40:51.579092 unpack-trees.c:512           | d0 | main                     | region_leave |     | 46.973662 |  0.000046 | unpack_trees | ....label:check_updates
12:40:51.579117 unpack-trees.c:2102          | d0 | main                     | region_leave | r1  | 46.973688 |  0.275965 | unpack_trees | ..label:unpack_trees
12:40:51.579129 unpack-trees.c:2105          | d0 | main                     | data         |     | 46.973699 |  0.276002 | unpack_trees | ..unpack_trees/nr_unpack_entries:0
12:40:51.579138 unpack-trees.c:2106          | d0 | main                     | region_leave |     | 46.973708 |  0.276011 | unpack_trees | label:unpack_trees
:100644 100644 32141822f4d028e026144fd488d464129eae848c 0000000000000000000000000000000000000000 M	otools/inc/apple/xcconfig/global_symbols.xcconfig
:100644 100644 208b947931eb3ea5234604bc047906f3fbdb4c41 0000000000000000000000000000000000000000 M	outlookmac/project/outlook.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
:100644 100644 2095952b9cff41f9dfd575f6c1cb0fd3bcdc8e78 0000000000000000000000000000000000000000 M	outlookmac/project/outlook.xcodeproj/xcshareddata/xcschemes/Build All Mac Debug.xcscheme
:100644 100644 4ad7060d1d37a1d551968041f52875511ff9b041 0000000000000000000000000000000000000000 M	outlookmac/project/outlook.xcodeproj/xcshareddata/xcschemes/Build Only Outlook Debug.xcscheme
:100644 100644 71da7506c728f7596fcd22e93004ba01fb7b1c29 0000000000000000000000000000000000000000 M	outlookmac/src/OlkCalendarUIKit/source/Protocols/ContextMenuProvider.swift
:100644 100644 325c6137ca5ec42c5d1dd5432565e75666b921b1 0000000000000000000000000000000000000000 M	outlookmac/src/OlkCalendarUIKit/source/Utilities/UserSettingsFactory.swift
:100644 100644 5f12073c2ed87d41bee4fb649df8a537ad9baa60 0000000000000000000000000000000000000000 M	outlookmac/src/entourage/resources/Base.lproj/CalendarView.xib
:100644 100644 13f21a622a30d4d01e7138c4f92ca02fc0dcc83c 0000000000000000000000000000000000000000 M	outlookmac/src/olkuikit/LocalizedStrings.swift
:100644 100644 5992f001a7c1744e14896d7abf950551a65ac70f 0000000000000000000000000000000000000000 M	outlookmac/src/olkuikit/categories/NSView+OlkUIKitAdditions.m
12:40:51.579376 git.c:796                    | d0 | main                     | exit         |     | 46.973945 |           |              | code:0
12:40:51.579408 tree-walk.c:189              | d0 | main                     | data_json    | r1  | 46.973978 | 46.973978 | traverse_tre | statistics:{"traverse_trees_count":1,"traverse_trees_max_depth":1}
12:40:51.579423 trace2/tr2_tgt_perf.c:215    | d0 | main                     | atexit       |     | 46.973994 |           |              | code:0

I also try the standard git(2.38.1), and it takes 96s.
>12:46:09.841110 sparse-index.c:340           | d0 | main                     | region_enter | r1  |  3.354133 |           | index        | ..label:ensure_full_index
12:46:24.250220 cache-tree.c:477             | d0 | main                     | region_enter | r1  | 17.763240 |           | cache_tree   | ....label:update
12:47:41.901972 cache-tree.c:482             | d0 | main                     | region_leave | r1  | 95.414993 | 77.651753 | cache_tree   | ....label:update
12:47:41.902005 sparse-index.c:422           | d0 | main                     | region_leave | r1  | 95.415028 | 92.060895 | index        | ..label:ensure_full_index 

 - If the problem was occurring with a specific repository, can you specify
   the repository?

   * [x] Office monorepo

**Comment by derrickstolee** [comment] 2022-11-29 14:29
This is essentially a duplicate of #542. Closing.

**Closed as completed by derrickstolee** 2022-11-29 14:29 UTC
