### ISSUE TITLE
`git merge` reports different result on Mac and Windows

### ISSUE THREAD

**Issue by wilbaker** [microsoft/git#63] opened 2018-10-26 23:23 UTC
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
On Mac: git version 2.19.0.gvfs.1.36.gb06df091a3
On Windows: git version 2.19.0.gvfs.1.34.gc7fb556
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD on Windows, Terminal on Mac

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
<clone the VFS for Git repo>
<Add wilbaker's fork as a remote>
git checkout dont_assert_on_file_attributes_merge_weirdness
git checkout merge_weirdness_master
git checkout dont_assert_on_file_attributes_merge_weirdness
git merge merge_weirdness_master
git status
```
 - What did you expect to occur after running these commands?

I expected that the output would be the same on both platforms, instead, it was only correct on Windows.

*Windows output*
```
C:\Repos\VFSForGit\src>git merge merge_weirdness_master
Removing Scripts/StopDevService.bat
Removing Scripts/StartDevService.bat
Removing Scripts/SetupDevService.bat
Auto-merging ProjFS.Mac/PrjFSKext/PrjFSKext/KauthHandler.cpp
CONFLICT (content): Merge conflict in ProjFS.Mac/PrjFSKext/PrjFSKext/KauthHandler.cpp
Automatic merge failed; fix conflicts and then commit the result.

C:\Repos\VFSForGit\src>git status
On branch dont_assert_on_file_attributes_merge_weirdness
Your branch is up-to-date with 'origin/dont_assert_on_file_attributes_merge_weirdness'.

You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Changes to be committed:

        modified:   .gitignore
        modified:   GVFS/FastFetch/CheckoutJob.cs
        modified:   GVFS/GVFS.Common/Git/DiffTreeResult.cs
        modified:   GVFS/GVFS.Common/Git/GitObjects.cs
        modified:   GVFS/GVFS.Common/Git/GitProcess.cs
        modified:   GVFS/GVFS.Common/Prefetch/BlobPrefetcher.cs
        modified:   GVFS/GVFS.Common/Prefetch/Git/DiffHelper.cs
        modified:   GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/PrefetchVerbWithoutSharedCacheTests.cs
        new file:   GVFS/GVFS.Tests/DataSources.cs
        modified:   GVFS/GVFS.UnitTests/Data/forward.txt
        new file:   GVFS/GVFS.UnitTests/Git/GitProcessTests.cs
        modified:   GVFS/GVFS.UnitTests/Prefetch/DiffHelperTests.cs
        modified:   GVFS/GVFS.UnitTests/Prefetch/DiffTreeResultTests.cs
        modified:   GVFS/GVFS.Virtualization/FileSystemCallbacks.cs
        modified:   ProjFS.Mac/PrjFSKext/PrjFSKext/VirtualizationRoots.cpp
        modified:   ProjFS.Mac/PrjFSKext/PrjFSKext/VirtualizationRoots.hpp
        modified:   ProjFS.Mac/PrjFSKext/PrjFSKext/VnodeUtilities.cpp
        modified:   ProjFS.Mac/PrjFSKext/PrjFSKext/VnodeUtilities.hpp
        modified:   Scripts/BuildGVFSForWindows.bat
        new file:   Scripts/InitializeEnvironment.bat
        modified:   Scripts/Mac/BuildGVFSForMac.sh
        modified:   Scripts/Mac/CleanupFunctionalTests.sh
        modified:   Scripts/Mac/DownloadGVFSGit.sh
        modified:   Scripts/Mac/GVFS_Clone.sh
        modified:   Scripts/Mac/GVFS_Mount.sh
        modified:   Scripts/Mac/GVFS_Unmount.sh
        modified:   Scripts/Mac/GetGitVersionNumber.sh
        new file:   Scripts/Mac/InitializeEnvironment.sh
        modified:   Scripts/Mac/NukeBuildOutputs.sh
        modified:   Scripts/Mac/PrepFunctionalTests.sh
        new file:   Scripts/Mac/PublishGit.sh
        modified:   Scripts/Mac/RunFunctionalTests.sh
        modified:   Scripts/NukeBuildOutputs.bat
        modified:   Scripts/ReinstallGVFS.bat
        modified:   Scripts/RestorePackages.bat
        modified:   Scripts/RunFunctionalTests.bat
        modified:   Scripts/RunUnitTests.bat
        deleted:    Scripts/SetupDevService.bat
        deleted:    Scripts/StartDevService.bat
        modified:   Scripts/StopAllServices.bat
        deleted:    Scripts/StopDevService.bat
        modified:   Scripts/UninstallGVFS.bat
        modified:   nuget.config

Unmerged paths:
  (use "git add <file>..." to mark resolution)

        both modified:   ProjFS.Mac/PrjFSKext/PrjFSKext/KauthHandler.cpp


```

 - What actually happened instead?

*Mac Output*

```
~/Repos/VFSForGit/src>git merge merge_weirdness_master
Removing Scripts/StopDevService.bat
Removing Scripts/StartDevService.bat
Removing Scripts/SetupDevService.bat
Auto-merging ProjFS.Mac/PrjFSKext/PrjFSKext/KauthHandler.cpp
CONFLICT (content): Merge conflict in ProjFS.Mac/PrjFSKext/PrjFSKext/KauthHandler.cpp
Automatic merge failed; fix conflicts and then commit the result.
~/Repos/VFSForGit/src>git status
On branch dont_assert_on_file_attributes_merge_weirdness
All conflicts fixed but you are still merging.
  (use "git commit" to conclude merge)

Changes to be committed:

	new file:   GVFS/GVFS.Tests/DataSources.cs
	new file:   GVFS/GVFS.UnitTests/Git/GitProcessTests.cs

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   .gitignore
	modified:   GVFS/FastFetch/CheckoutJob.cs
	modified:   GVFS/GVFS.Common/Git/DiffTreeResult.cs
	modified:   GVFS/GVFS.Common/Git/GitObjects.cs
	modified:   GVFS/GVFS.Common/Git/GitProcess.cs
	modified:   GVFS/GVFS.Common/Prefetch/BlobPrefetcher.cs
	modified:   GVFS/GVFS.Common/Prefetch/Git/DiffHelper.cs
	modified:   GVFS/GVFS.FunctionalTests/Tests/EnlistmentPerFixture/PrefetchVerbWithoutSharedCacheTests.cs
	modified:   GVFS/GVFS.UnitTests/Data/forward.txt
	modified:   GVFS/GVFS.UnitTests/Prefetch/DiffHelperTests.cs
	modified:   GVFS/GVFS.UnitTests/Prefetch/DiffTreeResultTests.cs
	modified:   GVFS/GVFS.Virtualization/FileSystemCallbacks.cs
	modified:   ProjFS.Mac/PrjFSKext/PrjFSKext/KauthHandler.cpp
	modified:   ProjFS.Mac/PrjFSKext/PrjFSKext/VirtualizationRoots.cpp
	modified:   ProjFS.Mac/PrjFSKext/PrjFSKext/VirtualizationRoots.hpp
	modified:   ProjFS.Mac/PrjFSKext/PrjFSKext/VnodeUtilities.cpp
	modified:   ProjFS.Mac/PrjFSKext/PrjFSKext/VnodeUtilities.hpp
	modified:   Scripts/BuildGVFSForWindows.bat
	modified:   Scripts/Mac/BuildGVFSForMac.sh
	modified:   Scripts/Mac/CleanupFunctionalTests.sh
	modified:   Scripts/Mac/DownloadGVFSGit.sh
	modified:   Scripts/Mac/GVFS_Clone.sh
	modified:   Scripts/Mac/GVFS_Mount.sh
	modified:   Scripts/Mac/GVFS_Unmount.sh
	modified:   Scripts/Mac/GetGitVersionNumber.sh
	modified:   Scripts/Mac/NukeBuildOutputs.sh
	modified:   Scripts/Mac/PrepFunctionalTests.sh
	modified:   Scripts/Mac/RunFunctionalTests.sh
	modified:   Scripts/NukeBuildOutputs.bat
	modified:   Scripts/ReinstallGVFS.bat
	modified:   Scripts/RestorePackages.bat
	modified:   Scripts/RunFunctionalTests.bat
	modified:   Scripts/RunUnitTests.bat
	deleted:    Scripts/SetupDevService.bat
	deleted:    Scripts/StartDevService.bat
	modified:   Scripts/StopAllServices.bat
	deleted:    Scripts/StopDevService.bat
	modified:   Scripts/UninstallGVFS.bat
	modified:   nuget.config

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	Scripts/InitializeEnvironment.bat
	Scripts/Mac/InitializeEnvironment.sh
	Scripts/Mac/PublishGit.sh


```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/wilbaker/VFSForGit

**Comment by dscho** [comment] 2018-11-09 08:35
> (read: `merge_weirdness_master` is an ancestor of `dont_assert_on_file_attributes`)

Oh shucks. I should learn how to read. Of course it reproduces here when I use the correct branch, `dont_assert_on_file_attributes_merge_weirdness`...

The thing is, I tried to reproduce this on Linux (actually, WSL), and the behavior matches the one of your Windows run.

Sadly, I do not have easy access to a Mac right now (the only way I could try to reproduce this is by running an Azure Pipeline), so may I ask you to try a couple of things, first of all: re-run the merge with a Git built from https://github.com/git/git's v2.19.1? The easiest way to do that is to clone that repository, check out the tag, build it, then run `(export GIT_EXEC_PATH=/path/to/new/clone; export PATH=$GIT_EXEC_PATH:$PATH; git merge merge_weirdness_master)`

**Comment by dscho** [comment] 2018-11-09 09:12
I had another hunch what the problem could be: line endings. And indeed, if I change (on Linux, where `core.autocrlf` is *not* `true`), say, `MirrorProvider/Scripts/Windows/Build.bat`, run `git status` to verify that it is modified, then revert the change manually, another `git status` will *still* show the file as modified, and the diff will show the `^M` corresponding to the Carriage Return of the CR/LF line ending.

I can see why those line endings are required for `.bat` files. To make that explicit, we should add this line to `.gitattributes`:

```
*.bat eol=crlf
```

There are a ton more files with CR/LF line endings, though, and as @ethomson [pointed out](https://www.edwardthomson.com/blog/git_for_windows_line_endings.html), all of their line endings conventions should be declared explicitly, in `.gitattributes`.

I see CR/LF line endings in files with these extensions: `.bat`, `.config`, `.cpp`, `.cs`, `.csproj`, `.filters`, `.gitattributes`, `.gitignore`, `.h`, `.iss`, `.md`, `.nuspec`, `.props`, `.rc`, `.sln`, `.StyleCop`, `.txt`, and `.vcxproj`.

I guess that `.bat`, `.config`, `.csproj`, `.filters`, `.rc`, `.sln` and `.vcxproj` should have CR/LF endings. But I would suggest that all of the others should not. So here is my proposal for `.gitattributes`:

```
# Windows Batch file
*.bat eol=crlf

# NuGet, .NET config files
*.config eol=crlf
*.nuspec eol=crlf

# Visual Studio files
*.csproj eol=crlf
*.filters eol=crlf
*.props eol=crlf
*.rc eol=crlf
*.sln eol=crlf
*.vcxproj eol=crlf

# XCode/Mac stuff
*.pbxproj eol=lf
*.plist eol=lf
*.xcscheme eol=lf
*.xcsettings eol=lf
*.xcworkspacedata eol=lf

# StyleCop
*.StyleCop eol=crlf

# Git files
*.gitattributes eol=lf
*.gitignore eol=lf

# C, C#, C++
*.c eol=lf
*.cpp eol=lf
*.cs eol=lf
*.h eol=lf
*.hpp eol=lf

# Shell scripts
*.sh eol=lf

# InnoSetup
*.iss eol=lf

# Text files
*.md eol=lf
*.txt eol=lf

# Test data
*.chk binary
*.edb binary
*.jfm binary
*.jrs binary
*.log binary

# Icon
*.ico binary
```

Then, to fix up the files which have incorrect line endings, run:

```sh
dos2unix $(git ls-files \*.cpp \*.cs \*.gitattributes \*.gitignore \*.h \*.iss \*.md \*.txt)
```

This will probably cause some ruckus, as it would most likely result in pretty much all PRs failing with merge conflicts...

**Comment by dscho** [comment] 2018-11-09 09:29
And https://github.com/Microsoft/VFSForGit/pull/497 is my attempt to implement this.

If it causes too many problems now, I can easily wait, and update the branch once the team is ready.

**Comment by dscho** [comment] 2019-01-18 11:53
Does this happen, still?

**Comment by wilbaker** [comment] 2019-01-18 18:30
I think @kewillford was able to track down something in git he thought might be responsible.

**Comment by dscho** [comment] 2019-01-23 16:00
Should we close this here, then?

**Comment by wilbaker** [comment] 2019-01-23 17:12
That'd be fine with me.

@jrbriggs @kewillford and objections to tracking this issue in https://github.com/Microsoft/VFSForGit/issues/522?

**Comment by kewillford** [comment] 2019-01-23 17:15
That is fine with me.  I am still digging into this one.  We need a consistent repro to really get to the bottom of the issue.

**Comment by derrickstolee** [comment] 2019-07-08 19:39
Closing as this seems to be fixed in M153.

**Closed by derrickstolee** 2019-07-08 19:39 UTC
Labels: bug
